[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["node_modules"]
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "@uniswap/v4-core/=node_modules/@uniswap/v4-core/",
  "@uniswap/v4-periphery/=node_modules/@uniswap/v4-periphery/",
  "permit2/=node_modules/@uniswap/v4-periphery/lib/permit2/",
  "forge-std/=node_modules/forge-std/src/"
]

[fuzz]
runs = 512

[invariant]
runs = 256
depth = 64
